export const EDEN_LOGO = 'https://i.imgur.com/rQmm1FM.png';
export const HEARDLE_URL = 'https://eden-heardle.io';

export const Colors = {
  CONFIRM: '32FF25',
  ERROR: 'DF0000',
  YELLOW: 'fffb25',
  INFO: 'f03200',
  MUSIC: 'f94c57',
  GIVEAWAY: '7CF3FF',
  GUESSTHESONG: 'fa57c1',
  DM: '7289da',
  BOOST: 'f47fff',
  HEARDLE: 'f9d72f',
  BIRTHDAY: 'ffffc5',
  TYPING: 'fdfaff',
  BLACK: '000001',
  RANDOM: 'Random',
  SPOTIFY: '1DB954',
  YOUTUBE: 'CD201F',
  QOTD: 'E6B83E'
};

export const ALL_SONGS = [
  '02:09',
  'End Credits',
  'Gravity',
  'Nocturne',
  'Interlude',
  'Wake Up',
  'catch me if you can',
  'Billie Jean',
  'sex',
  'drugs',
  'and',
  'rock + roll',
  'Fumes',
  'XO',
  'Circles',
  'wrong',
  'take care',
  'start//end',
  'wings',
  'icarus',
  'lost//found',
  'crash',
  'gold',
  'forever//over',
  'float',
  'wonder',
  'love; not wrong (brave)',
  'falling in reverse',
  'about time',
  'stutter',
  'all you need is love',
  'nowhere else',
  '909',
  'good morning',
  'in',
  'hertz',
  'static',
  'projector',
  'love, death, distraction',
  'how to sleep',
  'calm down',
  'just saying',
  'fomo',
  'so far so good',
  'isohel',
  'tides',
  'rushing',
  '$treams',
  '2020',
  'out',
  'untitled',
  'Peaked',
  'Cold Feet',
  'Stingray',
  'cant help',
  '🔒 (demo)',
  'A Call',
  'Balling',
  'Sci-Fi',
  'Modern Warfare',
  'Waiting Room',
  'Closer 2',
  'PS1',
  'Call Me Back',
  'Duvidha',
  'Elsewhere',
  'Reaching 2',
  'cant',
  'The Love U Need',
  'Zzz',
  '5ever'
];
